Exemplos parcialmente arrumados
- 'processo' não é uma lista nem um dicionário. Arrumado
- exemplos 001 e 005 funcionando: consultam o estado do serviço no SEFAZ
! exemplos 002 003 004 006 007 e 008 falhando (testado com Python 2.6.4 Ubuntu 9.10):

Ou apresentam o erro:

Traceback (most recent call last):
(...)
  File "/usr/local/lib/python2.6/dist-packages/xmlsec.py", line 458, in cryptoAppKeyLoad
    if ret is None: raise Error('xmlSecCryptoAppKeyLoad() failed')
xmlsec.Error: 'xmlSecCryptoAppKeyLoad() failed'

Ou o erro:

Traceback (most recent call last):
  File "003_versao_1.10_cancelar_nota.py", line 30, in <module>
    justificativa=u'Somente um teste de cancelamento')
TypeError: cancelar_nota() got an unexpected keyword argument 'protocolo'

--HG--
extra : rebase_source : 7212e2c8fa4f31ec7569cb9c57e91ba1f62afa23